project: "BraTS20"

model:
  features: [16, 32, 64, 128, 256]
  n_convs: [2, 2, 2, 2, 2]  
  in_channels: 4
  out_channels: 5
  downsample_mode: "conv"

training:
  epochs: 30
  train_batch_size: 2
  test_batch_size: 8
  accumulation_steps: 2
  lr: 0.0001
  weight_decay: 0.001
  seed: 42
  test_freq: 2

data:
  output_shape: [128, 128, 128]
  norm_type: "z"
  train_ratio: 0.8
  preprocessed_dir: "/content/processed"
  seg_mode: "preprocessed"
  assign_label5: true

loss:
  dice_weight: 1.0
  ce_weight: 0.0
  ignore_idxs_dice: null
  ignore_idxs_ce: [0]
  ce_class_weights: [0.0, 1.5727, 0.6086, 1.7897, 0.0290]
experiment:
  wandb_logging: true

hardware:
  device: "cuda"
  num_workers: 0